name: Run Tests and Build with Maven

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  AZURE_WEBAPP_NAME: aposta-api
  JAVA_VERSION: '11'
    
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Permissions for Maven Wrapper
        run: chmod +x mvnw

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11' # Change this to your desired Java version

      - name: Test with Maven
        run: ./mvnw clean test

        
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Construção de imagem de container da aplicação
        uses: docker/build-push-action@v5.0.0
        with: 
          context: ./src
          file: ./Dockerfile
          push: true
          tags: |
            mnosse/cicdgithubactions:latest
            mnosse/cicdgithubactions:v${{ github.run_number }}
        
